### ISSUE TITLE
Invoking DELETE endpoint for users returns method not allowed (405)

### ISSUE THREAD

**Issue by Jascha-N** [dccn-tg/filer-gateway#12]
Even though the API is documented, it is not accessible.

This causes a failure in the core-api `deleteAccount` mutation.

**Comment by hurngchunlee** [comment]
are you sure the user's home directory is already empty?  If it is not empty, this error message is expected.

**Comment by Jascha-N** [comment]
The home directory should not even exist as I'm pretty sure it was never created, so it should return 404. But even if it exists and is not empty it should not return 405. In that case it should probably return [422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) or 400. 

405 means the endpoint exists but the method (GET, POST, etc.) is not supported for the endpoint.

**Comment by hurngchunlee** [comment]
I will have a look. The suggestion of code 422 is also a good one. I will also change it in case the dir is not empty.

**Comment by Jascha-N** [comment]
Come to think about it, in the non-empty case, 403 (not allowed/forbidden) might also be acceptable. 

In the non-existing case I would still expect it to return 404.

**Comment by hurngchunlee** [comment]
The fix is provided in PR #13
